version: "3"
services:
  web:
    image: nginx:1.21.4-alpine
    command: nginx-debug -g 'daemon off;'
    volumes:
      - ./public:/public:ro
      - .docker/nginx.http.conf:/etc/nginx/conf.d/default.conf

    working_dir: /public
    depends_on:
      - app
    ports:
      - "8080:80"

    networks:
      - private
      - default

  app:
    image: decidim
    build:
      context: .
    volumes:
      - .:/home/decidim/app # or whatever is your workdir
    environment:
      - DB_HOST=pg
      - DB_USER=postgres
      - DB_PASSWORD=my-insecure-pw
      - RAILS_ENV=production
      - PORT=3000
      - RAILS_MAX_THREAD=5
    ports:
      - 3000:3000
    networks:
      - private
    depends_on:
      - pg

  pg:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=my-insecure-pw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=decidim
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - private
volumes:
  node_modules: {}
  pg-data: {}
networks:
  private:
    internal: true